name: Paper Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl-papers:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run paper crawler
      env:
        SEARCH_KEYWORDS: ${{ secrets.SEARCH_KEYWORDS }}
        JOURNAL_NAME: ${{ secrets.JOURNAL_NAME }}
      run: python paper_crawler.py
    
    - name: Copy index.html to papers
      run: cp index.html papers/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./papers
        publish_branch: gh-pages 